### ISSUE TITLE
Issue on page /ipynb/SchrodingerEq.html

### ISSUE THREAD

**Issue by kirstenentz** [QC-Edu/IntroQM2022#1]
Hi @PaulWAyers,

I noticed on 4.2.5 you have the TDSE written in blue, with a note saying that the blue term is the Hamiltonian operator. However, the whole equation is in blue, not just the operator. Thought you might want to fix that!

Kirsten

> P.S. I'm not sure if this method was the best way to notify you of this (i.e., as opposed to an MS Teams message or somewhere else on GitHub), so let me know!

**Comment by PaulWAyers** [comment]
Thanks @kirstenentz ! I fixed it and it will change in the next build of the web site.

The issue seems to be that the way that the "color" keyword worked has changed. I'm sure it's going to show up more places in the notes too.....
        https://docs.mathjax.org/en/latest/input/tex/extensions/color.html

**Comment by PaulWAyers** [comment]
@RichRick1 can you figure out what is wrong? It looks OK in the Notebook but not on the web site. 
    https://github.com/QC-Edu/IntroQM2022/blob/master/ipynb/SchrodingerEq.ipynb
Is the Web Site served using MathJax or KaTex (or actual Latex). That could be the issue.

**Comment by PaulWAyers** [comment]
Actually, I think that's the problem. MathJax 2 vs. 3. Can you upgrade to MathJax 3. We'll need that for bra-ket notation too.
https://jupyterbook.org/content/math.html
https://docs.mathjax.org/en/latest/input/tex/extensions/braket.html

**Comment by RichRick1** [comment]
@PaulWAyers  I'm working on it rn

**Comment by RichRick1** [comment]
@PaulWAyers Should work now. We'd already used MathJax3, the problem was with automatic reusing file from the `_build` folder. Deleting the folder and building book again helped:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/36164007/152003807-7471bddd-c484-4474-ab15-1ba6df709d10.png">
